### ISSUE TITLE
takePassenger can't update currentPassengerNumber

### ISSUE THREAD

**Issue by keremalan** [keremalan/dart_real_word_objects#1]
in vehicle folder, main.dart file contains "vehicle0.takePassenger(2);" command and when I run this code, currentPassengerNumber don't change.

**Comment by gazialankus** [comment]
You can link to lines this way
https://github.com/keremalan/dart_real_word_objects/blob/main/vehicles/main.dart#L67

This is best resolved by adding a breakpoint to this line and taking a look at the values of the variables
https://github.com/keremalan/dart_real_word_objects/blob/main/vehicles/main.dart#L37

I think you can do this yourself. If you haven't watched the lecture about debugging with breakpoints, maybe you should hold on until then. 

You should really use types in function parameters and return values. Otherwise variables/parameters end up with the `dynamic` type and this becomes a problem (also explained in lecture videos about types). A sample fix is in this pr https://github.com/keremalan/dart_real_word_objects/compare/main...gazialankus:patch-1

**Comment by srtcdncr** [comment]
You didn't assigned any type to takePassenger function's argument passengerNumber. If you assign type as int and change line 42 with following code it must be fixed. The fixed function below.

``` 
takePassenger(int passengerNumber) {
    if (currentPassengerNumber > passengerSeat) { // check avability of passengerSeat
      print("Seats can't take $passengerNumber people.");
    } else if (currentPassengerNumber == passengerNumber && doorIsLocked == true) { // passengerSeats are avaible and doors locked
      print("Passengers can't enter. Doors locked.");
    } else {
      currentPassengerNumber += passengerNumber; // add passengerNumber to currentPassengerNumber for calculate how much people in car
      print("$passengerNumber passenger enter your car.");
    }
  }
```

**Comment by keremalan** [comment]
@gazialankus I checked the line 67 and line 37 and understand what I did wrong. When we declare a function, should be use types in function parameters and return values.

I watched the videos about adding breakpoint and debugging, but I don't try on Android Studio, because using visual studio code for basic Dart codes. After read your comment, I looked up for debugging tools at vsc and try debugging, so I can saw how my code execute line by line. Thanks for your helps.

@srtcdncr before open a issue I was try += add to line 42, but take warning so I delete it. I need to check when I write function add type. Thank you too.
